import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  currency: string;
  setCurrency: (currency: string) => void;
  convertCurrency: (amount: number, fromCurrency: string, toCurrency: string) => number;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple currency conversion rates (in a real app, you'd fetch these from an API)
const currencyRates: { [key: string]: number } = {
  'USD': 1,
  'EUR': 0.85,
  'GBP': 0.73,
  'AED': 3.67,
  'SAR': 3.75,
  'QAR': 3.64,
  'KWD': 0.30,
  'JPY': 110.0,
  'CNY': 6.45
};

const translations = {
  en: {
    // Sidebar translations
    'sidebar.title': 'INSTALLIFY',
    'sidebar.subtitle': 'Freight & Logistics',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.shipments': 'Shipments',
    'sidebar.customers': 'Customers',
    'sidebar.accounting': 'Accounting',
    'sidebar.invoices': 'Invoices',
    'sidebar.cargo': 'Cargo',
    'sidebar.reports': 'Reports',
    'sidebar.settings': 'Settings',
    'sidebar.footer': 'Version 2.1.0',
    'sidebar.status': 'Online',

    // Header translations
    'header.title': 'INSTALLIFY Logistics',
    'header.search': 'Search...',
    'header.profile': 'Profile',

    // Dashboard translations
    'dashboard.title': 'Dashboard Overview',
    'dashboard.exportReport': 'Export Report',
    'dashboard.newShipment': 'New Shipment',
    'dashboard.activeShipments': 'Active Shipments',
    'dashboard.totalCustomers': 'Total Customers',
    'dashboard.monthlyRevenue': 'Monthly Revenue',
    'dashboard.growthRate': 'Growth Rate',
    'dashboard.fromLastMonth': 'from last month',
    'dashboard.recentShipments': 'Recent Shipments',
    'dashboard.alertsNotifications': 'Alerts & Notifications',
    'dashboard.shipmentDelayed': 'Shipment SH003 delayed',
    'dashboard.delayReason': 'Weather conditions at origin port',
    'dashboard.invoiceOverdue': 'Invoice #INV-2024-001 overdue',
    'dashboard.paymentPending': 'Payment pending for 5 days',
    'dashboard.newCustomer': 'New customer registration',
    'dashboard.customerVerification': 'Requires verification and approval',

    // Shipments Module
    'shipments.title': 'Shipment Management',
    'shipments.subtitle': 'Track and manage all your shipments',

    // Customers Module
    'customers.title': 'Customer Management',
    'customers.subtitle': 'Manage your client relationships',
    'customers.addCustomer': 'Add Customer',
    'customers.searchCustomers': 'Search customers...',
    'customers.filterCustomers': 'Filter',
    'customers.exportCustomers': 'Export',
    'customers.totalShipments': 'Total Shipments',
    'customers.totalValue': 'Total Value',
    'customers.lastShipment': 'Last Shipment',
    'customers.viewDetails': 'View Details',
    'customers.createQuote': 'Create Quote',

    // Accounting Module
    'accounting.title': 'Accounting & Finance',
    'accounting.subtitle': 'Financial management and reporting',
    'accounting.exportReports': 'Export Reports',
    'accounting.newTransaction': 'New Transaction',
    'accounting.totalRevenue': 'Total Revenue',
    'accounting.outstandingInvoices': 'Outstanding Invoices',
    'accounting.cashFlow': 'Cash Flow',
    'accounting.paymentProcessing': 'Payment Processing',
    'accounting.pendingPayments': 'pending payments',
    'accounting.positiveThisMonth': 'positive this month',
    'accounting.successRate': 'success rate',
    'accounting.recentTransactions': 'Recent Transactions',
    'accounting.chartOfAccounts': 'Chart of Accounts',
    'accounting.financialReports': 'Financial Reports',
    'accounting.profitLoss': 'Profit & Loss',
    'accounting.operatingExpenses': 'Operating Expenses',
    'accounting.ebitda': 'EBITDA',
    'accounting.netProfit': 'Net Profit',
    'accounting.balanceSheet': 'Balance Sheet',
    'accounting.totalAssets': 'Total Assets',
    'accounting.totalLiabilities': 'Total Liabilities',
    'accounting.equity': 'Equity',

    // Invoice translations
    'invoices.title': 'Invoice Management',
    'invoices.subtitle': 'Create and manage invoices',
    'invoices.create': 'Create Invoice',
    'invoices.bulkExport': 'Bulk Export',
    'invoices.totalInvoices': 'Total Invoices',
    'invoices.pendingAmount': 'Pending Amount',
    'invoices.overdueAmount': 'Overdue Amount',
    'invoices.collectionRate': 'Collection Rate',
    'invoices.thisMonth': 'This month',
    'invoices.onTimePayments': 'On-time payments',
    'invoices.all': 'All',
    'invoices.pending': 'Pending',
    'invoices.overdue': 'Overdue',
    'invoices.paid': 'Paid',
    'invoices.search': 'Search invoices...',
    'invoices.view': 'View',
    'invoices.edit': 'Edit',
    'invoices.send': 'Send',
    'invoices.pdf': 'PDF',
    'invoices.issueDate': 'Issue Date',
    'invoices.shipmentReference': 'Shipment Reference',
    'invoices.services': 'Services',

    // Cargo Module
    'cargo.title': 'Cargo Management',
    'cargo.subtitle': 'Track cargo and container operations',
    'cargo.volumeCalculator': 'Volume Calculator',
    'cargo.add': 'Add Cargo',
    'cargo.totalCargoItems': 'Total Cargo Items',
    'cargo.activeShipments': 'active shipments',
    'cargo.totalWeight': 'Total Weight',
    'cargo.totalVolume': 'Total Volume',
    'cargo.cubicMeters': 'cubic meters',
    'cargo.containerUtilization': 'Container Utilization',
    'cargo.averageEfficiency': 'average efficiency',
    'cargo.cargoItems': 'Cargo Items',
    'cargo.containerTypes': 'Container Types',
    'cargo.dimensionCalculator': 'Dimension Calculator',
    'cargo.search': 'Search cargo...',
    'cargo.dimensions': 'Dimensions',
    'cargo.weight': 'Weight',
    'cargo.volume': 'Volume',
    'cargo.container': 'Container',
    'cargo.temperatureRequirements': 'Temperature Requirements',
    'cargo.viewDetails': 'View Details',
    'cargo.editCargo': 'Edit Cargo',
    'cargo.calculateFreight': 'Calculate Freight',
    'cargo.internalDimensions': 'Internal Dimensions',
    'cargo.cargoCapacity': 'Cargo Capacity',
    'cargo.useForCalculation': 'Use for Calculation',
    'cargo.freightCalculator': 'Freight Calculator',
    'cargo.length': 'Length (cm)',
    'cargo.width': 'Width (cm)',
    'cargo.height': 'Height (cm)',
    'cargo.enterLength': 'Enter length',
    'cargo.enterWidth': 'Enter width',
    'cargo.enterHeight': 'Enter height',
    'cargo.actualWeight': 'Actual Weight (kg)',
    'cargo.quantity': 'Quantity',
    'cargo.enterActualWeight': 'Enter actual weight',
    'cargo.numberOfItems': 'Number of items',
    'cargo.calculateVolume': 'Calculate Volume',
    'cargo.calculateChargeableWeight': 'Calculate Chargeable Weight',
    'cargo.recommendContainer': 'Recommend Container',
    'cargo.calculatedVolume': 'Calculated Volume',
    'cargo.volumetricWeight': 'Volumetric Weight',
    'cargo.chargeableWeight': 'Chargeable Weight',

    // Reports Module
    'reports.title': 'Reports & Analytics',
    'reports.subtitle': 'Business intelligence and insights',
    'reports.export': 'Export',
    'reports.generate': 'Generate Report',
    'reports.onTimeDelivery': 'On-Time Delivery',
    'reports.shipmentVolume': 'Shipment Volume',
    'reports.averageTransitTime': 'Average Transit Time',
    'reports.customerSatisfaction': 'Customer Satisfaction',
    'reports.thisYear': 'this year',
    'reports.lastMonth': 'last month',
    'reports.days': 'days',
    'reports.reportCategories': 'Report Categories',
    'reports.scheduledReports': 'Scheduled Reports',
    'reports.customReports': 'Custom Reports',
    'reports.shipmentReports': 'Shipment Reports',
    'reports.financialReports': 'Financial Reports',
    'reports.customerReports': 'Customer Reports',
    'reports.operationalReports': 'Operational Reports',
    'reports.monthlyShipments': 'Monthly Shipments',
    'reports.revenueAnalysis': 'Revenue Analysis',
    'reports.customerAnalysis': 'Customer Analysis',
    'reports.performanceMetrics': 'Performance Metrics',
    'reports.cashFlowAnalysis': 'Cash Flow Analysis',
    'reports.customerGrowth': 'Customer Growth',
    'reports.resourceUtilization': 'Resource Utilization',
    'reports.last': 'Last',
    'reports.viewReport': 'View Report',
    'reports.monthlyRevenueReport': 'Monthly Revenue Report',
    'reports.everyFirstOfMonth': 'Every 1st of the month',
    'reports.next': 'Next',
    'reports.edit': 'Edit',
    'reports.downloadPdf': 'Download PDF',
    'reports.weeklyOperationsSummary': 'Weekly Operations Summary',
    'reports.everyMonday': 'Every Monday',
    'reports.customerPerformanceReport': 'Customer Performance Report',
    'reports.everyFifteenthOfMonth': 'Every 15th of the month',
    'reports.scheduleReport': 'Schedule Report',
    'reports.createCustomReport': 'Create Custom Report',
    'reports.reportName': 'Report Name',
    'reports.enterReportName': 'Enter report name',
    'reports.dataSource': 'Data Source',
    'reports.financial': 'Financial',
    'reports.operations': 'Operations',
    'reports.dateRange': 'Date Range',
    'reports.lastThirtyDays': 'Last 30 days',
    'reports.lastThreeMonths': 'Last 3 months',
    'reports.lastSixMonths': 'Last 6 months',
    'reports.lastYear': 'Last year',
    'reports.customRange': 'Custom range',
    'reports.reportFormat': 'Report Format',
    'reports.recentCustomReports': 'Recent Custom Reports',
    'reports.quarterlyPerformanceAnalysis': 'Q4 Performance Analysis',
    'reports.generated': 'Generated',
    'reports.customerRetentionReport': 'Customer Retention Report',
    'reports.routeEfficiencyAnalysis': 'Route Efficiency Analysis',

    // Status translations
    'status.paid': 'Paid',
    'status.pending': 'Pending',
    'status.overdue': 'Overdue',
    'status.draft': 'Draft',
    'status.intransit': 'In Transit',
    'status.delivered': 'Delivered',
    'status.loading': 'Loading',
    'status.customs': 'Customs',
    'status.active': 'Active',
  },
  ar: {
    // Arabic translations
    'sidebar.title': 'إنستاليفاي',
    'sidebar.subtitle': 'الشحن والخدمات اللوجستية',
    'sidebar.dashboard': 'لوحة القيادة',
    'sidebar.shipments': 'الشحنات',
    'sidebar.customers': 'العملاء',
    'sidebar.accounting': 'المحاسبة',
    'sidebar.invoices': 'الفواتير',
    'sidebar.cargo': 'البضائع',
    'sidebar.reports': 'التقارير',
    'sidebar.settings': 'الإعدادات',
    'sidebar.footer': 'الإصدار 2.1.0',
    'sidebar.status': 'متصل',

    // Header translations in Arabic
    'header.title': 'إنستاليفاي اللوجستيات',
    'header.search': 'البحث...',
    'header.profile': 'الملف الشخصي',

    // Dashboard translations in Arabic
    'dashboard.title': 'نظرة عامة على لوحة القيادة',
    'dashboard.exportReport': 'تصدير التقرير',
    'dashboard.newShipment': 'شحنة جديدة',
    'dashboard.activeShipments': 'الشحنات النشطة',
    'dashboard.totalCustomers': 'إجمالي العملاء',
    'dashboard.monthlyRevenue': 'الإيرادات الشهرية',
    'dashboard.growthRate': 'معدل النمو',
    'dashboard.fromLastMonth': 'من الشهر الماضي',
    'dashboard.recentShipments': 'الشحنات الأخيرة',
    'dashboard.alertsNotifications': 'التنبيهات والإشعارات',
    'dashboard.shipmentDelayed': 'تأخر الشحنة SH003',
    'dashboard.delayReason': 'الأحوال الجوية في ميناء المنشأ',
    'dashboard.invoiceOverdue': 'الفاتورة #INV-2024-001 متأخرة',
    'dashboard.paymentPending': 'الدفع معلق لمدة 5 أيام',
    'dashboard.newCustomer': 'تسجيل عميل جديد',
    'dashboard.customerVerification': 'يتطلب التحقق والموافقة',

    // Module titles in Arabic
    'shipments.title': 'إدارة الشحنات',
    'shipments.subtitle': 'تتبع وإدارة جميع شحناتك',

    'customers.title': 'إدارة العملاء',
    'customers.subtitle': 'إدارة علاقاتك مع العملاء',
    'customers.addCustomer': 'إضافة عميل',
    'customers.searchCustomers': 'البحث في العملاء...',
    'customers.filterCustomers': 'تصفية',
    'customers.exportCustomers': 'تصدير',
    'customers.totalShipments': 'إجمالي الشحنات',
    'customers.totalValue': 'إجمالي القيمة',
    'customers.lastShipment': 'آخر شحنة',
    'customers.viewDetails': 'عرض التفاصيل',
    'customers.createQuote': 'إنشاء عرض سعر',

    'accounting.title': 'المحاسبة والمالية',
    'accounting.subtitle': 'الإدارة المالية والتقارير',
    'accounting.exportReports': 'تصدير التقارير',
    'accounting.newTransaction': 'معاملة جديدة',
    'accounting.totalRevenue': 'إجمالي الإيرادات',
    'accounting.outstandingInvoices': 'الفواتير المعلقة',
    'accounting.cashFlow': 'التدفق النقدي',
    'accounting.paymentProcessing': 'معالجة المدفوعات',
    'accounting.pendingPayments': 'مدفوعات معلقة',
    'accounting.positiveThisMonth': 'إيجابي هذا الشهر',
    'accounting.successRate': 'معدل النجاح',
    'accounting.recentTransactions': 'المعاملات الأخيرة',
    'accounting.chartOfAccounts': 'دليل الحسابات',
    'accounting.financialReports': 'التقارير المالية',
    'accounting.profitLoss': 'الأرباح والخسائر',
    'accounting.operatingExpenses': 'المصروفات التشغيلية',
    'accounting.ebitda': 'الأرباح قبل الفوائد والضرائب',
    'accounting.netProfit': 'صافي الربح',
    'accounting.balanceSheet': 'الميزانية العمومية',
    'accounting.totalAssets': 'إجمالي الأصول',
    'accounting.totalLiabilities': 'إجمالي الخصوم',
    'accounting.equity': 'حقوق الملكية',

    'invoices.title': 'إدارة الفواتير',
    'invoices.subtitle': 'إنشاء وإدارة الفواتير',
    'invoices.create': 'إنشاء فاتورة',
    'invoices.bulkExport': 'تصدير مجمع',
    'invoices.totalInvoices': 'إجمالي الفواتير',
    'invoices.pendingAmount': 'المبلغ المعلق',
    'invoices.overdueAmount': 'المبلغ المتأخر',
    'invoices.collectionRate': 'معدل التحصيل',
    'invoices.thisMonth': 'هذا الشهر',
    'invoices.onTimePayments': 'المدفوعات في الوقت المحدد',
    'invoices.all': 'الكل',
    'invoices.pending': 'معلق',
    'invoices.overdue': 'متأخر',
    'invoices.paid': 'مدفوع',
    'invoices.search': 'البحث في الفواتير...',
    'invoices.view': 'عرض',
    'invoices.edit': 'تعديل',
    'invoices.send': 'إرسال',
    'invoices.pdf': 'PDF',
    'invoices.issueDate': 'تاريخ الإصدار',
    'invoices.shipmentReference': 'مرجع الشحنة',
    'invoices.services': 'الخدمات',

    'cargo.title': 'إدارة البضائع',
    'cargo.subtitle': 'تتبع عمليات البضائع والحاويات',
    'cargo.volumeCalculator': 'حاسبة الحجم',
    'cargo.add': 'إضافة بضاعة',
    'cargo.totalCargoItems': 'إجمالي عناصر البضائع',
    'cargo.activeShipments': 'شحنات نشطة',
    'cargo.totalWeight': 'إجمالي الوزن',
    'cargo.totalVolume': 'إجمالي الحجم',
    'cargo.cubicMeters': 'متر مكعب',
    'cargo.containerUtilization': 'استخدام الحاويات',
    'cargo.averageEfficiency': 'متوسط الكفاءة',
    'cargo.cargoItems': 'عناصر البضائع',
    'cargo.containerTypes': 'أنواع الحاويات',
    'cargo.dimensionCalculator': 'حاسبة الأبعاد',
    'cargo.search': 'البحث في البضائع...',
    'cargo.dimensions': 'الأبعاد',
    'cargo.weight': 'الوزن',
    'cargo.volume': 'الحجم',
    'cargo.container': 'الحاوية',
    'cargo.temperatureRequirements': 'متطلبات درجة الحرارة',
    'cargo.viewDetails': 'عرض التفاصيل',
    'cargo.editCargo': 'تعديل البضاعة',
    'cargo.calculateFreight': 'حساب الشحن',
    'cargo.internalDimensions': 'الأبعاد الداخلية',
    'cargo.cargoCapacity': 'سعة البضائع',
    'cargo.useForCalculation': 'استخدام للحساب',
    'cargo.freightCalculator': 'حاسبة الشحن',
    'cargo.length': 'الطول (سم)',
    'cargo.width': 'العرض (سم)',
    'cargo.height': 'الارتفاع (سم)',
    'cargo.enterLength': 'أدخل الطول',
    'cargo.enterWidth': 'أدخل العرض',
    'cargo.enterHeight': 'أدخل الارتفاع',
    'cargo.actualWeight': 'الوزن الفعلي (كغ)',
    'cargo.quantity': 'الكمية',
    'cargo.enterActualWeight': 'أدخل الوزن الفعلي',
    'cargo.numberOfItems': 'عدد العناصر',
    'cargo.calculateVolume': 'حساب الحجم',
    'cargo.calculateChargeableWeight': 'حساب الوزن القابل للشحن',
    'cargo.recommendContainer': 'اقتراح حاوية',
    'cargo.calculatedVolume': 'الحجم المحسوب',
    'cargo.volumetricWeight': 'الوزن الحجمي',
    'cargo.chargeableWeight': 'الوزن القابل للشحن',

    'reports.title': 'التقارير والتحليلات',
    'reports.subtitle': 'ذكاء الأعمال والرؤى',
    'reports.export': 'تصدير',
    'reports.generate': 'إنشاء تقرير',
    'reports.onTimeDelivery': 'التسليم في الوقت المحدد',
    'reports.shipmentVolume': 'حجم الشحنات',
    'reports.averageTransitTime': 'متوسط وقت النقل',
    'reports.customerSatisfaction': 'رضا العملاء',
    'reports.thisYear': 'هذا العام',
    'reports.lastMonth': 'الشهر الماضي',
    'reports.days': 'أيام',
    'reports.reportCategories': 'فئات التقارير',
    'reports.scheduledReports': 'التقارير المجدولة',
    'reports.customReports': 'التقارير المخصصة',
    'reports.shipmentReports': 'تقارير الشحنات',
    'reports.financialReports': 'التقارير المالية',
    'reports.customerReports': 'تقارير العملاء',
    'reports.operationalReports': 'التقارير التشغيلية',
    'reports.monthlyShipments': 'الشحنات الشهرية',
    'reports.revenueAnalysis': 'تحليل الإيرادات',
    'reports.customerAnalysis': 'تحليل العملاء',
    'reports.performanceMetrics': 'مقاييس الأداء',
    'reports.cashFlowAnalysis': 'تحليل التدفق النقدي',
    'reports.customerGrowth': 'نمو العملاء',
    'reports.resourceUtilization': 'استخدام الموارد',
    'reports.last': 'آخر',
    'reports.viewReport': 'عرض التقرير',
    'reports.monthlyRevenueReport': 'تقرير الإيرادات الشهرية',
    'reports.everyFirstOfMonth': 'كل أول يوم في الشهر',
    'reports.next': 'التالي',
    'reports.edit': 'تعديل',
    'reports.downloadPdf': 'تحميل PDF',
    'reports.weeklyOperationsSummary': 'ملخص العمليات الأسبوعية',
    'reports.everyMonday': 'كل يوم اثنين',
    'reports.customerPerformanceReport': 'تقرير أداء العملاء',
    'reports.everyFifteenthOfMonth': 'كل 15 من الشهر',
    'reports.scheduleReport': 'جدولة تقرير',
    'reports.createCustomReport': 'إنشاء تقرير مخصص',
    'reports.reportName': 'اسم التقرير',
    'reports.enterReportName': 'أدخل اسم التقرير',
    'reports.dataSource': 'مصدر البيانات',
    'reports.financial': 'مالي',
    'reports.operations': 'عمليات',
    'reports.dateRange': 'النطاق الزمني',
    'reports.lastThirtyDays': 'آخر 30 يوماً',
    'reports.lastThreeMonths': 'آخر 3 أشهر',
    'reports.lastSixMonths': 'آخر 6 أشهر',
    'reports.lastYear': 'العام الماضي',
    'reports.customRange': 'نطاق مخصص',
    'reports.reportFormat': 'تنسيق التقرير',
    'reports.recentCustomReports': 'التقارير المخصصة الأخيرة',
    'reports.quarterlyPerformanceAnalysis': 'تحليل أداء الربع الرابع',
    'reports.generated': 'تم إنشاؤه',
    'reports.customerRetentionReport': 'تقرير الاحتفاظ بالعملاء',
    'reports.routeEfficiencyAnalysis': 'تحليل كفاءة المسار',

    // Additional Arabic translations
    'settings.emailNotifications': 'إشعارات البريد الإلكتروني',
    'settings.smsNotifications': 'إشعارات الرسائل النصية',
    'settings.shipmentAlerts': 'تنبيهات الشحنات',
    'settings.invoiceReminders': 'تذكيرات الفواتير',
    'settings.systemUpdates': 'تحديثات النظام',
    'settings.mobileAlerts': 'التنبيهات المحمولة',
    'settings.enabled': 'مفعل',
    'settings.disabled': 'معطل',
    'settings.userAccounts': 'حسابات المستخدمين',
    'settings.addUser': 'إضافة مستخدم',
    'settings.admin': 'مشرف',
    'settings.manager': 'مدير',
    'settings.operator': 'مشغل',
    'settings.active': 'نشط',
    'settings.inactive': 'غير نشط',
    'settings.apiIntegrations': 'تكاملات API',
    'settings.connected': 'متصل',
    'settings.disconnected': 'غير متصل',
    'settings.configure': 'تكوين',
    'settings.lastSync': 'آخر مزامنة',
    'settings.testConnection': 'اختبار الاتصال',
    'settings.saveConfiguration': 'حفظ التكوين',
    'settings.configureIntegrationSettings': 'قم بتكوين إعدادات التكامل أدناه',
    'settings.smtpServer': 'خادم SMTP',
    'settings.enterSmtpServer': 'أدخل خادم SMTP',
    'settings.port': 'المنفذ',
    'settings.encryption': 'التشفير',
    'settings.username': 'اسم المستخدم',
    'settings.enterEmail': 'أدخل عنوان البريد الإلكتروني',
    'settings.password': 'كلمة المرور',
    'settings.enterPassword': 'أدخل كلمة المرور',
    'settings.apiEndpoint': 'نقطة نهاية API',
    'settings.enterApiEndpoint': 'أدخل نقطة نهاية API',
    'settings.apiKey': 'مفتاح API',
    'settings.enterApiKey': 'أدخل مفتاح API',
    'settings.region': 'المنطقة',
    'settings.selectRegion': 'اختر المنطقة',
    'settings.shippingLines': 'خطوط الشحن',
    'settings.selectShippingLine': 'اختر خط الشحن',
    'settings.provider': 'المزود',
    'settings.senderNumber': 'رقم المرسل',
    'settings.enterSenderNumber': 'أدخل رقم المرسل',
    'settings.webhookUrl': 'رابط Webhook',
    'settings.enterWebhookUrl': 'أدخل رابط Webhook',
    'settings.noConfigurationAvailable': 'لا توجد خيارات تكوين متاحة لهذا التكامل.',

    'status.paid': 'مدفوع',
    'status.pending': 'معلق',
    'status.overdue': 'متأخر',
    'status.draft': 'مسودة',
    'status.intransit': 'في الطريق',
    'status.delivered': 'تم التسليم',
    'status.loading': 'جاري التحميل',
    'status.customs': 'الجمارك',
    'status.active': 'نشط',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [currency, setCurrency] = useState('USD');

  // Load saved settings from localStorage
  useEffect(() => {
    const savedSettings = localStorage.getItem('logiscrm-settings');
    if (savedSettings) {
      try {
        const parsed = JSON.parse(savedSettings);
        if (parsed.currency) {
          setCurrency(parsed.currency.split(' - ')[0]); // Extract currency code
        }
      } catch (error) {
        console.error('Error loading currency from settings:', error);
      }
    }
  }, []);

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key] || key;
  };

  const convertCurrency = (amount: number, fromCurrency: string, toCurrency: string): number => {
    if (fromCurrency === toCurrency) return amount;
    
    // Convert to USD first, then to target currency
    const usdAmount = amount / currencyRates[fromCurrency];
    return Math.round(usdAmount * currencyRates[toCurrency] * 100) / 100;
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t, 
      currency, 
      setCurrency, 
      convertCurrency 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
