import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    sidebar: {
      dashboard: "Dashboard",
      shipments: "Shipments",
      customers: "Customers",
      accounting: "Accounting",
      invoices: "Invoices",
      cargo: "Cargo",
      reports: "Reports",
      settings: "Settings",
      footer: "InstallFy @2025 Developed by",
      developer: "Jalal Nasser",
      status: "Operational",
    },
    dashboard: {
      title: "Dashboard",
      activeShipments: "Active Shipments",
      totalCustomers: "Total Customers",
      monthlyRevenue: "Monthly Revenue",
      growthRate: "Growth Rate",
      fromLastMonth: "from last month",
      recentShipments: "Recent Shipments",
      alertsNotifications: "Alerts & Notifications",
      shipmentDelayed: "Shipment SH003 Delayed",
      delayReason: "Weather conditions at port",
      invoiceOverdue: "Invoice INV-2024-001 Overdue",
      paymentPending: "Payment pending for 5 days",
      newCustomer: "New Customer Registration",
      customerVerification: "Requires verification",
      exportReport: "Export Report",
      newShipment: "New Shipment"
    },
    customers: {
      title: "Customers",
      addCustomer: "Add Customer",
      searchCustomers: "Search customers...",
      filterCustomers: "Filter",
      exportCustomers: "Export",
      totalShipments: "Total Shipments",
      totalValue: "Total Value",
      lastShipment: "Last Shipment",
      viewDetails: "View Details",
      createQuote: "Create Quote"
    },
    accounting: {
      title: "Accounting",
      exportReports: "Export Reports",
      newTransaction: "New Transaction",
      totalRevenue: "Total Revenue",
      outstandingInvoices: "Outstanding Invoices",
      cashFlow: "Cash Flow",
      paymentProcessing: "Payment Processing",
      pendingPayments: "pending payments",
      positiveThisMonth: "positive this month",
      successRate: "success rate",
      recentTransactions: "Recent Transactions",
      chartOfAccounts: "Chart of Accounts",
      financialReports: "Financial Reports",
      profitLoss: "Profit & Loss Statement",
      operatingExpenses: "Operating Expenses",
      ebitda: "EBITDA",
      netProfit: "Net Profit",
      balanceSheet: "Balance Sheet",
      totalAssets: "Total Assets",
      totalLiabilities: "Total Liabilities",
      equity: "Shareholders' Equity"
    },
    invoices: {
      title: "Invoices",
      bulkExport: "Bulk Export",
      create: "Create Invoice",
      totalInvoices: "Total Invoices",
      pendingAmount: "Pending Amount",
      overdueAmount: "Overdue Amount",
      collectionRate: "Collection Rate",
      thisMonth: "this month",
      all: "All",
      pending: "Pending",
      overdue: "Overdue",
      paid: "Paid",
      onTimePayments: "on-time payments",
      search: "Search invoices...",
      issueDate: "Issue Date",
      shipmentReference: "Shipment Reference",
      services: "Services",
      view: "View",
      edit: "Edit",
      send: "Send",
      pdf: "PDF"
    },
    cargo: {
      title: "Cargo",
      volumeCalculator: "Volume Calculator",
      add: "Add Cargo",
      totalCargoItems: "Total Cargo Items",
      activeShipments: "active shipments",
      totalWeight: "Total Weight",
      totalVolume: "Total Volume",
      cubicMeters: "cubic meters",
      containerUtilization: "Container Utilization",
      averageEfficiency: "average efficiency",
      cargoItems: "Cargo Items",
      containerTypes: "Container Types",
      dimensionCalculator: "Dimension Calculator",
      search: "Search cargo...",
      dimensions: "Dimensions",
      weight: "Weight",
      volume: "Volume",
      container: "Container",
      temperatureRequirements: "Temperature Requirements",
      viewDetails: "View Details",
      editCargo: "Edit Cargo",
      calculateFreight: "Calculate Freight",
      internalDimensions: "Internal Dimensions",
      cargoCapacity: "Cargo Capacity",
      useForCalculation: "Use for Calculation",
      freightCalculator: "Freight Calculator",
      length: "Length (cm)",
      enterLength: "Enter length",
      width: "Width (cm)",
      enterWidth: "Enter width",
      height: "Height (cm)",
      enterHeight: "Enter height",
      actualWeight: "Actual Weight (kg)",
      enterActualWeight: "Enter actual weight",
      quantity: "Quantity",
      numberOfItems: "Number of items",
      calculateVolume: "Calculate Volume",
      calculateChargeableWeight: "Calculate Chargeable Weight",
      recommendContainer: "Recommend Container",
      calculatedVolume: "Calculated Volume",
      volumetricWeight: "Volumetric Weight",
      chargeableWeight: "Chargeable Weight"
    },
    reports: {
      title: "Reports",
      export: "Export All",
      generate: "Generate Report",
      onTimeDelivery: "On-Time Delivery",
      shipmentVolume: "Shipment Volume",
      thisYear: "this year",
      lastMonth: "last month",
      days: "days",
      averageTransitTime: "Average Transit Time",
      customerSatisfaction: "Customer Satisfaction",
      reportCategories: "Report Categories",
      scheduledReports: "Scheduled Reports",
      customReports: "Custom Reports",
      shipmentReports: "Shipment Reports",
      monthlyShipments: "Monthly Shipments Summary",
      shipmentVolumeReport: "Shipment Volume Analysis",
      financialReports: "Financial Reports",
      revenueAnalysis: "Revenue Analysis",
      profitLossReport: "Profit & Loss Report",
      cashFlowAnalysis: "Cash Flow Analysis",
      customerReports: "Customer Reports",
      customerAnalysis: "Customer Analysis",
      customerGrowthReport: "Customer Growth",
      operationalReports: "Operational Reports",
      performanceMetrics: "Performance Metrics",
      resourceUtilization: "Resource Utilization",
      last: "Last generated",
      viewReport: "View",
      monthlyRevenueReport: "Monthly Revenue Report",
      everyFirstOfMonth: "Every 1st of month",
      next: "Next",
      weeklyOperationsSummary: "Weekly Operations Summary",
      everyMonday: "Every Monday",
      customerPerformanceReport: "Customer Performance Report",
      everyFifteenthOfMonth: "Every 15th of month",
      edit: "Edit",
      downloadPdf: "Download PDF",
      scheduleReport: "Schedule New Report",
      createCustomReport: "Create Custom Report",
      reportName: "Report Name",
      enterReportName: "Enter report name",
      dataSource: "Data Source",
      financial: "Financial",
      operations: "Operations",
      dateRange: "Date Range",
      lastThirtyDays: "Last 30 days",
      lastThreeMonths: "Last 3 months",
      lastSixMonths: "Last 6 months",
      lastYear: "Last year",
      customRange: "Custom range",
      reportFormat: "Report Format",
      recentCustomReports: "Recent Custom Reports",
      quarterlyPerformanceAnalysis: "Quarterly Performance Analysis",
      generated: "Generated",
      customerRetentionReport: "Customer Retention Report",
      routeEfficiencyAnalysis: "Route Efficiency Analysis"
    },
    settings: {
      title: "Settings",
      save: "Save Changes",
      saveSuccess: "Settings Saved",
      saveSuccessMessage: "Your settings have been successfully saved.",
      general: "General",
      notifications: "Notifications",
      users: "Users",
      integrations: "Integrations",
      companyInfo: "Company Information",
      logo: "Company Logo",
      uploadLogo: "Upload Logo",
      companyName: "Company Name",
      address: "Address",
      phone: "Phone",
      email: "Email",
      website: "Website",
      systemPreferences: "System Preferences",
      timezone: "Timezone",
      currency: "Currency",
      dateFormat: "Date Format",
      emailNotifications: "Email Notifications",
      shipmentAlerts: "Shipment Alerts",
      invoiceReminders: "Invoice Reminders",
      systemUpdates: "System Updates",
      enabled: "Enabled",
      disabled: "Disabled",
      smsNotifications: "SMS Notifications",
      mobileAlerts: "Mobile Alerts",
      userAccounts: "User Accounts",
      addUser: "Add User",
      admin: "Admin",
      manager: "Manager",
      operator: "Operator",
      active: "Active",
      inactive: "Inactive",
      apiIntegrations: "API Integrations",
      configure: "Configure",
      lastSync: "Last Sync",
      configureIntegrationSettings: "Configure integration settings",
      testConnection: "Test Connection",
      saveConfiguration: "Save Configuration",
      smtpServer: "SMTP Server",
      enterSmtpServer: "Enter SMTP Server",
      port: "Port",
      encryption: "Encryption",
      username: "Username",
      enterEmail: "Enter Email",
      password: "Password",
      enterPassword: "Enter Password",
      apiEndpoint: "API Endpoint",
      enterApiEndpoint: "Enter API Endpoint",
      apiKey: "API Key",
      enterApiKey: "Enter API Key",
      region: "Region",
      selectRegion: "Select Region",
      shippingLines: "Shipping Lines",
      selectShippingLine: "Select Shipping Line",
      provider: "Provider",
      senderNumber: "Sender Number",
      enterSenderNumber: "Enter Sender Number",
      webhookUrl: "Webhook URL",
      enterWebhookUrl: "Enter Webhook URL",
      noConfigurationAvailable: "No configuration available for this integration.",
      logoUploadedSuccessfully: "Logo uploaded successfully",
      shipmentAlertsDescription: "Receive updates on shipment status changes",
      invoiceRemindersDescription: "Automated payment reminders",
      systemUpdatesDescription: "System maintenance and updates",
      mobileAlertsDescription: "Critical alerts via SMS",
      customerNotifications: "Customer Notifications",
      customerNotificationsDescription: "Send SMS updates to customers",
      emergencyAlerts: "Emergency Alerts",
      emergencyAlertsDescription: "System failures and emergencies",
      customsApiDescription: "Real-time customs clearance updates",
      shippingLinesApiDescription: "Container tracking and schedules",
      paymentGatewayDescription: "Online payment processing",
      smsServiceDescription: "SMS notifications and alerts",
      emailServiceDescription: "Email delivery service for notifications",
      sidebarTitle: "Sidebar Title",
      sidebarSubtitle: "Sidebar Subtitle"
    },
    shipments: {
      title: "Shipments",
      customer: "Customer"
    },
    status: {
      active: "Active",
      pending: "Pending",
      paid: "Paid",
      completed: "Completed",
      delivered: "Delivered",
      intransit: "In Transit",
      loading: "Loading",
      customs: "Customs",
      overdue: "Overdue"
    }
  },
  ar: {
    sidebar: {
      dashboard: "لوحة القيادة",
      shipments: "الشحنات",
      customers: "العملاء",
      accounting: "المحاسبة",
      invoices: "الفواتير",
      cargo: "بضائع",
      reports: "التقارير",
      settings: "إعدادات",
      footer: "InstallFy @2025 تطوير",
      developer: "جلال ناصر",
      status: "التشغيلية",
    },
    dashboard: {
      title: "لوحة القيادة",
      activeShipments: "الشحنات النشطة",
      totalCustomers: "إجمالي العملاء",
      monthlyRevenue: "الإيرادات الشهرية",
      growthRate: "معدل النمو",
      fromLastMonth: "من الشهر الماضي",
      recentShipments: "الشحنات الأخيرة",
      alertsNotifications: "التنبيهات والإشعارات",
      shipmentDelayed: "تأخر الشحنة SH003",
      delayReason: "ظروف جوية في الميناء",
      invoiceOverdue: "فاتورة INV-2024-001 متأخرة",
      paymentPending: "دفعة معلقة لمدة 5 أيام",
      newCustomer: "تسجيل عميل جديد",
      customerVerification: "يتطلب التحقق",
      exportReport: "تصدير التقرير",
      newShipment: "شحنة جديدة"
    },
    customers: {
      title: "العملاء",
      addCustomer: "إضافة عميل",
      searchCustomers: "البحث عن العملاء...",
      filterCustomers: "تصفية",
      exportCustomers: "تصدير",
      totalShipments: "إجمالي الشحنات",
      totalValue: "القيمة الإجمالية",
      lastShipment: "آخر شحنة",
      viewDetails: "عرض التفاصيل",
      createQuote: "إنشاء عرض أسعار"
    },
    accounting: {
      title: "المحاسبة",
      exportReports: "تصدير التقارير",
      newTransaction: "معاملة جديدة",
      totalRevenue: "إجمالي الإيرادات",
      outstandingInvoices: "الفواتير المعلقة",
      cashFlow: "التدفق النقدي",
      paymentProcessing: "معالجة المدفوعات",
      pendingPayments: "المدفوعات المعلقة",
      positiveThisMonth: "إيجابي هذا الشهر",
      successRate: "معدل النجاح",
      recentTransactions: "المعاملات الأخيرة",
      chartOfAccounts: "دليل الحسابات",
      financialReports: "التقارير المالية",
      profitLoss: "بيان الأرباح والخسائر",
      operatingExpenses: "المصاريف التشغيلية",
      ebitda: "الأرباح قبل الفوائد والضرائب",
      netProfit: "صافي الربح",
      balanceSheet: "الميزانية العمومية",
      totalAssets: "إجمالي الأصول",
      totalLiabilities: "إجمالي الخصوم",
      equity: "حقوق المساهمين"
    },
    invoices: {
      title: "الفواتير",
      bulkExport: "تصدير مجمع",
      create: "إنشاء فاتورة",
      totalInvoices: "إجمالي الفواتير",
      pendingAmount: "المبلغ المعلق",
      overdueAmount: "المبلغ المتأخر",
      collectionRate: "معدل التحصيل",
      thisMonth: "هذا الشهر",
      all: "الكل",
      pending: "معلق",
      overdue: "متأخر",
      paid: "مدفوع",
      onTimePayments: "المدفوعات في الوقت المحدد",
      search: "البحث في الفواتير...",
      issueDate: "تاريخ الإصدار",
      shipmentReference: "مرجع الشحنة",
      services: "الخدمات",
      view: "عرض",
      edit: "تحرير",
      send: "إرسال",
      pdf: "PDF"
    },
    cargo: {
      title: "البضائع",
      volumeCalculator: "حاسبة الحجم",
      add: "إضافة بضائع",
      totalCargoItems: "إجمالي عناصر البضائع",
      activeShipments: "الشحنات النشطة",
      totalWeight: "إجمالي الوزن",
      totalVolume: "إجمالي الحجم",
      cubicMeters: "متر مكعب",
      containerUtilization: "استخدام الحاويات",
      averageEfficiency: "متوسط الكفاءة",
      cargoItems: "عناصر البضائع",
      containerTypes: "أنواع الحاويات",
      dimensionCalculator: "حاسبة الأبعاد",
      search: "البحث في البضائع...",
      dimensions: "الأبعاد",
      weight: "الوزن",
      volume: "الحجم",
      container: "الحاوية",
      temperatureRequirements: "متطلبات درجة الحرارة",
      viewDetails: "عرض التفاصيل",
      editCargo: "تحرير البضائع",
      calculateFreight: "حساب الشحن",
      internalDimensions: "الأبعاد الداخلية",
      cargoCapacity: "سعة البضائع",
      useForCalculation: "استخدم للحساب",
      freightCalculator: "حاسبة الشحن",
      length: "الطول (سم)",
      enterLength: "أدخل الطول",
      width: "العرض (سم)",
      enterWidth: "أدخل العرض",
      height: "الارتفاع (سم)",
      enterHeight: "أدخل الارتفاع",
      actualWeight: "الوزن الفعلي (كجم)",
      enterActualWeight: "أدخل الوزن الفعلي",
      quantity: "الكمية",
      numberOfItems: "عدد العناصر",
      calculateVolume: "حساب الحجم",
      calculateChargeableWeight: "حساب الوزن القابل للشحن",
      recommendContainer: "اقتراح حاوية",
      calculatedVolume: "الحجم المحسوب",
      volumetricWeight: "الوزن الحجمي",
      chargeableWeight: "الوزن القابل للشحن"
    },
    reports: {
      title: "التقارير",
      export: "تصدير الكل",
      generate: "إنشاء تقرير",
      onTimeDelivery: "التسليم في الوقت المحدد",
      shipmentVolume: "حجم الشحنات",
      thisYear: "هذا العام",
      lastMonth: "الشهر الماضي",
      days: "أيام",
      averageTransitTime: "متوسط وقت النقل",
      customerSatisfaction: "رضا العملاء",
      reportCategories: "فئات التقارير",
      scheduledReports: "التقارير المجدولة",
      customReports: "التقارير المخصصة",
      shipmentReports: "تقارير الشحنات",
      monthlyShipments: "ملخص الشحنات الشهرية",
      shipmentVolumeReport: "تحليل حجم الشحنات",
      financialReports: "التقارير المالية",
      revenueAnalysis: "تحليل الإيرادات",
      profitLossReport: "تقرير الأرباح والخسائر",
      cashFlowAnalysis: "تحليل التدفق النقدي",
      customerReports: "تقارير العملاء",
      customerAnalysis: "تحليل العملاء",
      customerGrowthReport: "نمو العملاء",
      operationalReports: "التقارير التشغيلية",
      performanceMetrics: "مقاييس الأداء",
      resourceUtilization: "استخدام الموارد",
      last: "آخر إنشاء",
      viewReport: "عرض",
      monthlyRevenueReport: "تقرير الإيرادات الشهرية",
      everyFirstOfMonth: "كل أول الشهر",
      next: "التالي",
      weeklyOperationsSummary: "ملخص العمليات الأسبوعية",
      everyMonday: "كل يوم اثنين",
      customerPerformanceReport: "تقرير أداء العملاء",
      everyFifteenthOfMonth: "كل 15 من الشهر",
      edit: "تحرير",
      downloadPdf: "تحميل PDF",
      scheduleReport: "جدولة تقرير جديد",
      createCustomReport: "إنشاء تقرير مخصص",
      reportName: "اسم التقرير",
      enterReportName: "أدخل اسم التقرير",
      dataSource: "مصدر البيانات",
      financial: "مالي",
      operations: "العمليات",
      dateRange: "النطاق الزمني",
      lastThirtyDays: "آخر 30 يوماً",
      lastThreeMonths: "آخر 3 أشهر",
      lastSixMonths: "آخر 6 أشهر",
      lastYear: "العام الماضي",
      customRange: "نطاق مخصص",
      reportFormat: "تنسيق التقرير",
      recentCustomReports: "التقارير المخصصة الأخيرة",
      quarterlyPerformanceAnalysis: "تحليل الأداء الربعي",
      generated: "تم إنشاؤه",
      customerRetentionReport: "تقرير الاحتفاظ بالعملاء",
      routeEfficiencyAnalysis: "تحليل كفاءة المسار"
    },
    settings: {
      title: "إعدادات",
      save: "حفظ التغييرات",
      saveSuccess: "تم حفظ الإعدادات",
      saveSuccessMessage: "تم حفظ الإعدادات بنجاح.",
      general: "عام",
      notifications: "إشعارات",
      users: "المستخدمون",
      integrations: "عمليات التكامل",
      companyInfo: "معلومات الشركة",
      logo: "شعار الشركة",
      uploadLogo: "تحميل الشعار",
      companyName: "اسم الشركة",
      address: "عنوان",
      phone: "هاتف",
      email: "بريد إلكتروني",
      website: "موقع إلكتروني",
      systemPreferences: "تفضيلات النظام",
      timezone: "و المنطقة الزمنية",
      currency: "عملة",
      dateFormat: "صيغة التاريخ",
      emailNotifications: "إشعارات البريد الإلكتروني",
      shipmentAlerts: "تنبيهات الشحن",
      invoiceReminders: "تذكير الفواتير",
      systemUpdates: "تحديثات النظام",
      enabled: "مفعل",
      disabled: "معطل",
      smsNotifications: "إشعارات الرسائل القصيرة",
      mobileAlerts: "تنبيهات الجوال",
      userAccounts: "حسابات المستخدمين",
      addUser: "إضافة مستخدم",
      admin: "مدير",
      manager: "مدير",
      operator: "مشغل",
      active: "نشط",
      inactive: "غير نشط",
      apiIntegrations: "عمليات تكامل API",
      configure: "تكوين",
      lastSync: "آخر مزامنة",
      configureIntegrationSettings: "تكوين إعدادات التكامل",
      testConnection: "اختبار الاتصال",
      saveConfiguration: "حفظ التكوين",
      smtpServer: "خادم SMTP",
      enterSmtpServer: "أدخل خادم SMTP",
      port: "منفذ",
      encryption: "تشفير",
      username: "اسم المستخدم",
      enterEmail: "أدخل البريد الإلكتروني",
      password: "كلمة المرور",
      enterPassword: "أدخل كلمة المرور",
      apiEndpoint: "نقطة نهاية API",
      enterApiEndpoint: "أدخل نقطة نهاية API",
      apiKey: "مفتاح API",
      enterApiKey: "أدخل مفتاح API",
      region: "منطقة",
      selectRegion: "اختر المنطقة",
      shippingLines: "خطوط الشحن",
      selectShippingLine: "اختر خط الشحن",
      provider: "مزود",
      senderNumber: "رقم المرسل",
      enterSenderNumber: "أدخل رقم المرسل",
      webhookUrl: "عنوان URL الخاص بـ Webhook",
      enterWebhookUrl: "أدخل عنوان URL الخاص بـ Webhook",
      noConfigurationAvailable: "لا يوجد تكوين متاح لهذا التكامل.",
      logoUploadedSuccessfully: "تم رفع الشعار بنجاح",
      shipmentAlertsDescription: "تلقي تحديثات حول تغييرات حالة الشحنة",
      invoiceRemindersDescription: "تذكيرات الدفع الآلية",
      systemUpdatesDescription: "صيانة وتحديثات النظام",
      mobileAlertsDescription: "التنبيهات الحرجة عبر الرسائل النصية",
      customerNotifications: "إشعارات SMS للعملاء",
      customerNotificationsDescription: "إرسال تحديثات SMS للعملاء",
      emergencyAlerts: "تنبيهات الطوارئ",
      emergencyAlertsDescription: "أعطال النظام والطوارئ",
      customsApiDescription: "تحديثات التخليص الجمركي في الوقت الفعلي",
      shippingLinesApiDescription: "تتبع الحاويات والجداول الزمنية",
      paymentGatewayDescription: "معالجة المدفوعات عبر الإنترنت",
      smsServiceDescription: "إشعارات وتنبيهات الرسائل النصية",
      emailServiceDescription: "خدمة تسليم البريد الإلكتروني للإشعارات",
      sidebarTitle: "عنوان الشريط الجانبي",
      sidebarSubtitle: "العنوان الفرعي للشريط الجانبي"
    },
    shipments: {
      title: "الشحنات",
      customer: "العميل"
    },
    status: {
      active: "نشط",
      pending: "معلق",
      paid: "مدفوع",
      completed: "مكتمل",
      delivered: "تم التسليم",
      intransit: "في الطريق",
      loading: "تحميل",
      customs: "جمارك",
      overdue: "متأخر"
    }
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<string>(localStorage.getItem('language') || 'en');

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.setAttribute('lang', language);
    document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language as keyof typeof translations];
    for (const k of keys) {
      value = value?.[k];
      if (value === undefined) {
        return key;
      }
    }
    return value || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
