// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://domqhdjelvlwgfddhfen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvbXFoZGplbHZsd2dmZGRoZmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDI5MTcsImV4cCI6MjA2NDQ3ODkxN30.kUqhqYU4M0OZMKENoZPpPeqkP-4Rt2eT8KZR24q1eOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);